version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: telegram-messaging-api
        ports:
            - "8000:80"
        environment:
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=telegram_db
            - DB_USERNAME=root
            - DB_PASSWORD=password
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        container_name: telegram-messaging-api

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: telegram_db
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_AUTH_PLUGIN: mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        container_name: mysql-db

volumes:
    db_data:
        driver: local
